class  C2
{
	int test()
	{
		try
		{
			
		}
		catch(ArithmeticException ex)
		{
			return 10;
		}
		finally
		{
		}
		return 40;
	}
}
